# fly.toml file generated for wb-arena on 2024-09-05T17:45:23-03:00

app = "wb-arena"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "gig"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


[experimental]
  auto_rollback = true
  enable_consul = true

[[mounts]]
  source = "data_machines"
  destination = "/data"
  processes = ["app"]

[[statics]]
  guest_path = "/app/build/client/.vite"
  url_prefix = "/.vite"

[[statics]]
  guest_path = "/app/build/client/assets"
  url_prefix = "/assets"

[[statics]]
  guest_path = "/app/build/client/fonts"
  url_prefix = "/fonts"

[[statics]]
  guest_path = "/app/build/client/images"
  url_prefix = "/images"

[[statics]]
  guest_path = "/app/build/client/favicons"
  url_prefix = "/favicons"



[[services]]
  protocol = "tcp"
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    hard_limit = 200
    soft_limit = 150

  [[services.http_checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "1m0s"
    method = "get"
    path = "/healthcheck"
    protocol = "http"