# fly.toml app configuration file generated for kcd on 2023-06-30T11:21:22-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wb-arena"
primary_region = "gig"
kill_signal = "SIGINT"
kill_timeout = "5s"
swap_size_mb = 512

[experimental]
  auto_rollback = true
  enable_consul = true

[[mounts]]
  source = "data_machines"
  destination = "/data"
  processes = ["app"]

[[statics]]
  guest_path = "/app/build/client/.vite"
  url_prefix = "/.vite"

[[statics]]
  guest_path = "/app/build/client/assets"
  url_prefix = "/assets"

[[statics]]
  guest_path = "/app/build/client/fonts"
  url_prefix = "/fonts"

[[statics]]
  guest_path = "/app/build/client/images"
  url_prefix = "/images"

[[statics]]
  guest_path = "/app/build/client/favicons"
  url_prefix = "/favicons"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "requests"
    hard_limit = 200
    soft_limit = 150

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 6

  [[services.http_checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "1m0s"
    restart_limit = 0
    method = "get"
    path = "/healthcheck"
    protocol = "http"

  [[services.http_checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/litefs/health"